[package]
name = "gia"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
rouille = "3"
chrono = "0.4"
image = "0.25"
mime_guess = "2"
tera = "1"
serde = { version = "1", features = ["derive"] }
bcrypt = "0.15"
lettre = { version = "0.11", features = ["smtp-transport", "builder"] }
wkhtmltopdf = "0.4"
base64 = "0.22"
oneshot = "0.1"
dotenvy = "0.15"
